spring:
  datasource:
    url: jdbc:h2:mem:spring-beans-explained
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      data-locations:
        - classpath*:users.sql
        - classpath*:orders.sql
        - classpath*:items.sql
logging:
  pattern:
    console: "%-5level %logger: %msg%n"